version: '3'
services:
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    networks:
      - frontend
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ${WWW_ROOT}:/www
  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    volumes:
      - ${WWW_ROOT}:/www
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
networks:
  frontend:
  backend:
volumes:
    db:
