version: '3'
services:
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    image: ${COMPOSE_PROJECT_NAME:-caesar}_nginx:${PROJECT_NGINX_VERSION:-latest}-nginx-${NGINX_VERSION:-latest}
    networks:
      - frontend
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ${WWW_ROOT}:/www
  php:
    build:
      context: ./php
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME:-caesar}_php:${PROJECT_PHP_VERSION:-latest}-php-${PHP_VERSION:-latest}-fpm
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    volumes:
      - ${WWW_ROOT}:/www
networks:
  frontend:
  backend:
volumes:
    db:
