NewFilesHTMLOnly``x1
DisableHTML``x0
ShowNewsControls``x0
HeadlineNumber``x0
EnableHeadlines``x0
SiteLink``xhttp://caesar.logiqx.com/
htmlfile_path``x/sites/logiqx.com/caesar/news
DateFormat``x<Field: Weekday> <Field: Day> <Field: Month_Name>
Modify_ItemsPerPage``x20
SiteTitle``xCAESAR
glossdat``xNewsPro|~|<a href="http://amphibian.gagames.com/newspro/">NewsPro</a>
userdata``xlogiqx~YGM/dG4X5a4MA~logiqx@logiqx.com~3|rob~PBOZCcs7uHlvw~rob@logiqx.com~1|pi~QXr6DU1uK8KQo~pi@logiqx.com~1|peterd~EW8R4h4cVmEbA~peterd@emuhq.com~1
arclinkfile``xarclinks.txt
admin_path``x/sites/logiqx.com/caesar/cgi/newspro
showreadme``xno
NumberLimit``x0
CreateAnchors``x1
MaxSearchResults``x30
EmailSubject``xNews Update
EmailFrom``xlogiqx@logiqx.com
ArcHtmlExt``xtxt
ArcTime``x2
CommercialUser``x0
TimeOffset``x5
UseCookies``x0
archive_path``x/sites/logiqx.com/caesar/news
AutoLinkURL``x1
Daylight_Time_Zone``xBST
EnableBROption``x0
mainpagelimit``x2592000
12HourClock``x1
DisplayLink``x0
firsttime``xno
EmailTo``xlogiqx@logiqx.com
NewsArcDel``x2
BasicLayout``x0
CheckFileTime``x1
currentversion``x3.7.5
ArchiveNumber``x0
currentbuild``x32
EnableGlossary``x0
Standard_Time_Zone``xGMT
AutoBuild``x1
NewsAge``x30
