--
-- Files Tables
--

DROP TABLE IF EXISTS tmp_image;
CREATE TABLE tmp_image
(
	path		VARCHAR(20) NOT NULL,
	name		VARCHAR(20) NOT NULL,
	bytes		MEDIUMINT UNSIGNED NOT NULL,
	width		SMALLINT UNSIGNED NOT NULL,
	height		SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY	(path, name)
);

DROP TABLE IF EXISTS tmp_snap;
CREATE TABLE tmp_snap
(
	path		VARCHAR(40) NOT NULL,
	name		VARCHAR(40) NOT NULL,
	bytes		MEDIUMINT UNSIGNED NOT NULL,
	width		SMALLINT UNSIGNED NOT NULL,
	height		SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY	(path, name)
);

DROP TABLE IF EXISTS tmp_zip;
CREATE TABLE tmp_zip
(
	path		VARCHAR(60) NOT NULL,
	name		VARCHAR(60) NOT NULL,
	bytes		INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY	(path, name)
);

